version: '3.1'

volumes:
  data: {}
  cache:
    driver: local

services:
  db:
    image: postgres
    restart: always
    container_name: test-db-${NODE_ENV}
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_HOST: ${DATABASE_HOST}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - data:/var/lib/postgresql/data